apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: caokdks2z-nodejs-gitops
  description: This is GitOps manifest for caokdks2z-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=caokdks2z-nodejs
    backstage.io/kubernetes-id: caokdks2z-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: caokdks2z-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:caokdks2z-nodejs
